// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoEmaV9fQkENhnAoskKiIthnRtpWKcdpo',
    appId: '1:955115573436:web:7a8e3f4ecc51b128e0c0b9',
    messagingSenderId: '955115573436',
    projectId: 'irestaurant-245be',
    authDomain: 'irestaurant-245be.firebaseapp.com',
    storageBucket: 'irestaurant-245be.appspot.com',
    measurementId: 'G-CDDHHQ49LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNQpju8wsdNyCOl8NCrC1j0H1yliF_5Eo',
    appId: '1:955115573436:android:aae34679bc5f0325e0c0b9',
    messagingSenderId: '955115573436',
    projectId: 'irestaurant-245be',
    storageBucket: 'irestaurant-245be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXvoUxMgsbQrlNRBJDKgzGwA43NYse6x8',
    appId: '1:955115573436:ios:56c09191490149b5e0c0b9',
    messagingSenderId: '955115573436',
    projectId: 'irestaurant-245be',
    storageBucket: 'irestaurant-245be.appspot.com',
    iosBundleId: 'tuckkenn.irestaurant',
  );
}
